export const TABLE_RESIZE = "TABLE_RESIZE";
export const CHANGE_TEXT = "CHANGE_TEXT";
export const CHANGE_TABLE_HEADER = "CHANGE_TABLE_HEADER";
export const APPLY_STYLE = "APPLY_STYLE";
export const CURRENT_STYLE = "CURRENT_STYLE";
export const UPDATE_VIEW_DATE = "UPDATE_VIEW_DATE";
